# Generated by Django 4.0.4 on 2023-12-01 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_floorplan_seatings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seating',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee'),
        ),
    ]
