# Generated by Django 4.0.4 on 2023-12-01 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_seating_id_alter_seating_seating_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seating',
            name='floorPlan_id',
        ),
        migrations.DeleteModel(
            name='FloorPlan',
        ),
    ]
