# Generated by Django 4.0.4 on 2023-12-01 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_seating_floorplan_id_delete_floorplan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seating',
            options={'ordering': ['seating_id'], 'verbose_name': 'Seating', 'verbose_name_plural': 'Seatings'},
        ),
    ]
